# Generated by Django 3.1.3 on 2020-11-09 10:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品數量')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
            ],
            options={
                'verbose_name': '訂單商品',
                'verbose_name_plural': '訂單商品',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=30, unique=True, verbose_name='訂單號')),
                ('trade_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='交易號')),
                ('pay_status', models.CharField(choices=[('success', '成功'), ('cancel', '取消'), ('paying', '待支付')], max_length=100, verbose_name='訂單狀態')),
                ('pay_script', models.CharField(max_length=50, verbose_name='訂單留言')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='訂單金額')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付時間')),
                ('address', models.CharField(default='', max_length=100, verbose_name='收貨地址')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='收件人')),
                ('signer_mobile', models.CharField(max_length=10, verbose_name='聯絡電話')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品數量')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '購物車',
                'verbose_name_plural': '購物車',
            },
        ),
    ]
