# Generated by Django 3.1.3 on 2020-11-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20201109_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '訂單', 'verbose_name_plural': '訂單'},
        ),
    ]
