# Generated by Django 3.1.3 on 2020-11-09 10:08

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='品牌名', max_length=50, verbose_name='品牌名')),
                ('desc', models.TextField(default='', help_text='品牌描述', max_length=300, verbose_name='品牌描述')),
                ('image', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='使否刪除')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sh', models.CharField(default='', max_length=50, verbose_name='商品唯一編號')),
                ('name', models.CharField(max_length=300, verbose_name='商品名')),
                ('click_num', models.IntegerField(default=0, verbose_name='點擊量')),
                ('sold_num', models.IntegerField(default=0, verbose_name='銷售量')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏量')),
                ('goods_num', models.IntegerField(default=0, verbose_name='庫存量')),
                ('shop_price', models.FloatField(default=0, verbose_name='本店價格')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='商品簡介')),
                ('goods_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='內容')),
                ('ship_free', models.BooleanField(default=True, verbose_name='是否承擔運費')),
                ('goods_front_image', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面圖')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_home', models.BooleanField(default=False, verbose_name='是否熱銷')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='圖片')),
                ('image_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='圖片連接')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='商品', to='goods.goods', verbose_name='')),
            ],
            options={
                'verbose_name': '商品輪播圖',
                'verbose_name_plural': '商品輪播圖',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='類別名', max_length=30, verbose_name='類別名')),
                ('code', models.CharField(default='', help_text='類別code', max_length=30, verbose_name='類別code')),
                ('desc', models.TextField(default='', help_text='類別描述', verbose_name='類別描述')),
                ('category_type', models.IntegerField(choices=[(1, '一級類目 '), (2, '二級類目 '), (3, '三級類目 ')], help_text='類目級別', verbose_name='類目級別')),
                ('is_tab', models.BooleanField(default=False, help_text='是否導航', verbose_name='是否導航')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cat', to='goods.goodscategory', verbose_name='父類別')),
            ],
            options={
                'verbose_name': '商品類別',
                'verbose_name_plural': '商品類別',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goodscategory', verbose_name='商品類目'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='輪播圖片')),
                ('index', models.IntegerField(default=0, verbose_name='輪播順序')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '輪播商品',
                'verbose_name_plural': '輪播商品',
            },
        ),
    ]
