# Generated by Django 3.1.3 on 2020-11-09 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='', max_length=50, verbose_name='區域')),
                ('address', models.CharField(default='', max_length=100, verbose_name='詳細地址')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='收件人')),
                ('signer_mobile', models.CharField(default='', max_length=10, verbose_name='聯絡電話')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
            ],
            options={
                'verbose_name': '收貨地址',
                'verbose_name_plural': '收貨地址',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
            ],
            options={
                'verbose_name': '用戶收藏',
                'verbose_name_plural': '用戶收藏',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, '留言'), (2, '詢問'), (3, '售後'), (4, '求購')], default=1, help_text='留言類型: 1(留言),2(詢問),3(售後),4(求購)', verbose_name='留言類型')),
                ('subject', models.CharField(default='', max_length=80, verbose_name='主題')),
                ('message', models.TextField(default='', help_text='留言內容', verbose_name='留言內容')),
                ('file', models.FileField(help_text='上傳的文件', upload_to='', verbose_name='上傳的文件')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否刪除')),
            ],
            options={
                'verbose_name': '用戶留言',
                'verbose_name_plural': '用戶留言',
            },
        ),
    ]
